/**
 * Puthia Digital Platform — Call Signaling Service
 * 
 * Manages WebRTC signaling via Firebase Firestore real-time listeners:
 * - Creates & tracks Call session documents
 * - Handles SDP Offer & Answer exchanges
 * - Streams ICE Candidates across caller & callee subcollections
 * - Listens for incoming call invites & state updates in real-time
 */

import { 
  collection, 
  doc, 
  setDoc, 
  getDoc, 
  updateDoc, 
  onSnapshot, 
  addDoc, 
  query, 
  where, 
  orderBy, 
  limit, 
  Unsubscribe,
  serverTimestamp
} from "firebase/firestore";
import { db } from "../firebase";
import { CallData, CallStatus, CallType, CallParticipant } from "./webrtcService";

export interface SignalingOffer {
  type: RTCSdpType;
  sdp: string;
}

export interface SignalingAnswer {
  type: RTCSdpType;
  sdp: string;
}

export interface SignalingCandidatePayload {
  candidate: string;
  sdpMid?: string | null;
  sdpMLineIndex?: number | null;
  usernameFragment?: string | null;
  createdAt?: number;
}

export interface SignalingListenerCallbacks {
  onOffer?: (offer: RTCSessionDescriptionInit) => void;
  onAnswer?: (answer: RTCSessionDescriptionInit) => void;
  onRestartOffer?: (offer: RTCSessionDescriptionInit) => void;
  onRestartAnswer?: (answer: RTCSessionDescriptionInit) => void;
  onCandidate?: (candidate: RTCIceCandidateInit, source: 'caller' | 'callee') => void;
  onStatusChange?: (status: CallStatus, data: CallData) => void;
  onUpdate?: (data: CallData) => void;
  onError?: (error: Error) => void;
}

export interface NetworkInterruptionWatcherOptions {
  callId: string;
  peerConnection: RTCPeerConnection;
  isCaller: boolean;
  onInterrupted?: (reason?: string) => void;
  onReconnecting?: (attempt: number, maxAttempts: number) => void;
  onReconnected?: () => void;
  onReconnectionFailed?: (reason: string) => void;
  maxAttempts?: number;
  retryIntervalMs?: number;
  debounceMs?: number;
}

export interface NetworkInterruptionWatcher {
  cleanup: () => void;
  restartIceNow: () => Promise<boolean>;
  getIsReconnecting: () => boolean;
  getAttemptsCount: () => number;
}

export class CallSignalingService {
  private activeSubscriptions: Map<string, Unsubscribe[]> = new Map();

  /**
   * Helper to store active listener unsubscribes for automated teardown
   */
  private registerSubscription(callId: string, unsub: Unsubscribe) {
    const list = this.activeSubscriptions.get(callId) || [];
    list.push(unsub);
    this.activeSubscriptions.set(callId, list);
  }

  /**
   * Create a new call signaling document in Firestore (Caller initialization)
   */
  async createCallSession(
    caller: CallParticipant,
    receiver: CallParticipant,
    type: CallType,
    offer?: RTCSessionDescriptionInit
  ): Promise<{ callId: string; callData: CallData }> {
    try {
      const callDocRef = doc(collection(db, "calls"));
      const callId = callDocRef.id;

      const callData: CallData = {
        id: callId,
        callerId: caller.uid,
        callerName: caller.name || "ব্যবহারকারী",
        callerPhoto: caller.photoURL || "",
        receiverId: receiver.uid,
        receiverName: receiver.name || "ব্যবহারকারী",
        receiverPhoto: receiver.photoURL || "",
        type,
        status: "ringing",
        createdAt: Date.now(),
        ...(offer ? { offer: { type: offer.type, sdp: offer.sdp } } : {})
      };

      await setDoc(callDocRef, callData);
      return { callId, callData };
    } catch (error: any) {
      console.error("[CallSignalingService] Error creating call session:", error);
      throw error;
    }
  }

  /**
   * Update the SDP offer on an existing call session document
   */
  async setOffer(callId: string, offer: RTCSessionDescriptionInit): Promise<void> {
    try {
      const callDocRef = doc(db, "calls", callId);
      await updateDoc(callDocRef, {
        offer: {
          type: offer.type,
          sdp: offer.sdp
        },
        status: "ringing"
      });
    } catch (error: any) {
      console.error(`[CallSignalingService] Error setting offer for call ${callId}:`, error);
      throw error;
    }
  }

  /**
   * Update the SDP answer on an existing call session document (Callee response)
   */
  async setAnswer(callId: string, answer: RTCSessionDescriptionInit): Promise<void> {
    try {
      const callDocRef = doc(db, "calls", callId);
      await updateDoc(callDocRef, {
        answer: {
          type: answer.type,
          sdp: answer.sdp
        },
        status: "connected",
        connectedAt: Date.now()
      });
    } catch (error: any) {
      console.error(`[CallSignalingService] Error setting answer for call ${callId}:`, error);
      throw error;
    }
  }

  /**
   * Send a local ICE candidate generated by the Caller to Firestore
   */
  async sendCallerCandidate(callId: string, candidate: RTCIceCandidate): Promise<void> {
    if (!callId || !candidate) return;
    try {
      const callerCandidatesCol = collection(db, `calls/${callId}/callerCandidates`);
      await addDoc(callerCandidatesCol, {
        ...candidate.toJSON(),
        createdAt: Date.now()
      });
    } catch (error: any) {
      console.warn(`[CallSignalingService] Error sending caller candidate for ${callId}:`, error);
    }
  }

  /**
   * Send a local ICE candidate generated by the Callee to Firestore
   */
  async sendCalleeCandidate(callId: string, candidate: RTCIceCandidate): Promise<void> {
    if (!callId || !candidate) return;
    try {
      const calleeCandidatesCol = collection(db, `calls/${callId}/calleeCandidates`);
      await addDoc(calleeCandidatesCol, {
        ...candidate.toJSON(),
        createdAt: Date.now()
      });
    } catch (error: any) {
      console.warn(`[CallSignalingService] Error sending callee candidate for ${callId}:`, error);
    }
  }

  /**
   * Update Call Status (e.g. 'ringing', 'connecting', 'connected', 'ended', 'rejected', 'missed', 'busy')
   */
  async updateCallStatus(
    callId: string, 
    status: CallStatus, 
    extraPayload?: Partial<CallData>
  ): Promise<void> {
    if (!callId) return;
    try {
      const callDocRef = doc(db, "calls", callId);
      const updates: any = {
        status,
        ...extraPayload
      };
      if (status === "ended" || status === "rejected" || status === "missed") {
        updates.endedAt = Date.now();
      } else if (status === "connected" && !extraPayload?.connectedAt) {
        updates.connectedAt = Date.now();
      }
      await updateDoc(callDocRef, updates);
    } catch (error: any) {
      console.warn(`[CallSignalingService] Error updating call status (${status}) for ${callId}:`, error);
    }
  }

  /**
   * Retrieve single call data by ID
   */
  async getCallData(callId: string): Promise<CallData | null> {
    if (!callId) return null;
    try {
      const callDocRef = doc(db, "calls", callId);
      const snap = await getDoc(callDocRef);
      if (!snap.exists()) return null;
      return { ...(snap.data() as CallData), id: snap.id };
    } catch (error) {
      console.error(`[CallSignalingService] Error fetching call ${callId}:`, error);
      return null;
    }
  }

  /**
   * Real-time listener on call document changes (Offer, Answer, Status)
   */
  listenToCall(callId: string, callbacks: SignalingListenerCallbacks): Unsubscribe {
    const callDocRef = doc(db, "calls", callId);

    const unsub = onSnapshot(
      callDocRef,
      (snapshot) => {
        if (!snapshot.exists()) return;
        const data = snapshot.data() as CallData;
        const callData: CallData = { ...data, id: snapshot.id };

        if (callbacks.onUpdate) {
          callbacks.onUpdate(callData);
        }

        if (callbacks.onStatusChange && data.status) {
          callbacks.onStatusChange(data.status, callData);
        }

        if (callbacks.onOffer && data.offer) {
          callbacks.onOffer(data.offer);
        }

        if (callbacks.onAnswer && data.answer) {
          callbacks.onAnswer(data.answer);
        }

        if (callbacks.onRestartOffer && data.restartOffer) {
          callbacks.onRestartOffer(data.restartOffer);
        }

        if (callbacks.onRestartAnswer && data.restartAnswer) {
          callbacks.onRestartAnswer(data.restartAnswer);
        }
      },
      (error) => {
        console.error(`[CallSignalingService] Listen error for call ${callId}:`, error);
        callbacks.onError?.(error);
      }
    );

    this.registerSubscription(callId, unsub);
    return unsub;
  }

  /**
   * Real-time listener for Callee ICE Candidates (Used by Caller)
   */
  listenToCalleeCandidates(
    callId: string,
    onCandidate: (candidate: RTCIceCandidateInit) => void
  ): Unsubscribe {
    const calleeCandidatesCol = collection(db, `calls/${callId}/calleeCandidates`);

    const unsub = onSnapshot(calleeCandidatesCol, (snapshot) => {
      snapshot.docChanges().forEach((change) => {
        if (change.type === "added") {
          const data = change.doc.data();
          if (data.candidate) {
            onCandidate({
              candidate: data.candidate,
              sdpMid: data.sdpMid,
              sdpMLineIndex: data.sdpMLineIndex,
              usernameFragment: data.usernameFragment
            });
          }
        }
      });
    });

    this.registerSubscription(callId, unsub);
    return unsub;
  }

  /**
   * Real-time listener for Caller ICE Candidates (Used by Callee)
   */
  listenToCallerCandidates(
    callId: string,
    onCandidate: (candidate: RTCIceCandidateInit) => void
  ): Unsubscribe {
    const callerCandidatesCol = collection(db, `calls/${callId}/callerCandidates`);

    const unsub = onSnapshot(callerCandidatesCol, (snapshot) => {
      snapshot.docChanges().forEach((change) => {
        if (change.type === "added") {
          const data = change.doc.data();
          if (data.candidate) {
            onCandidate({
              candidate: data.candidate,
              sdpMid: data.sdpMid,
              sdpMLineIndex: data.sdpMLineIndex,
              usernameFragment: data.usernameFragment
            });
          }
        }
      });
    });

    this.registerSubscription(callId, unsub);
    return unsub;
  }

  /**
   * Real-time listener for Incoming Calls for a specific receiver UID
   */
  listenToIncomingCalls(
    userId: string,
    onIncomingCall: (call: CallData) => void,
    onCallDismissed?: () => void
  ): Unsubscribe {
    if (!userId) return () => {};

    const q = query(
      collection(db, "calls"),
      where("receiverId", "==", userId),
      where("status", "==", "ringing"),
      orderBy("createdAt", "desc"),
      limit(1)
    );

    return onSnapshot(q, (snapshot) => {
      if (!snapshot.empty) {
        const docSnap = snapshot.docs[0];
        const data = docSnap.data() as CallData;
        onIncomingCall({ ...data, id: docSnap.id });
      } else {
        if (onCallDismissed) {
          onCallDismissed();
        }
      }
    }, (err) => {
      console.warn("[CallSignalingService] Incoming call listener error:", err);
    });
  }

  /**
   * Send an ICE Restart SDP Offer to Firestore (Initiated when network interruption is detected)
   */
  async sendIceRestartOffer(callId: string, offer: RTCSessionDescriptionInit): Promise<void> {
    if (!callId || !offer) return;
    try {
      const callDocRef = doc(db, "calls", callId);
      await updateDoc(callDocRef, {
        restartOffer: {
          type: offer.type,
          sdp: offer.sdp
        },
        status: "reconnecting"
      });
      console.log(`[CallSignalingService] Sent ICE restart offer for call ${callId}`);
    } catch (error) {
      console.error(`[CallSignalingService] Error sending ICE restart offer for call ${callId}:`, error);
    }
  }

  /**
   * Send an ICE Restart SDP Answer to Firestore (Responder to ICE restart offer)
   */
  async sendIceRestartAnswer(callId: string, answer: RTCSessionDescriptionInit): Promise<void> {
    if (!callId || !answer) return;
    try {
      const callDocRef = doc(db, "calls", callId);
      await updateDoc(callDocRef, {
        restartAnswer: {
          type: answer.type,
          sdp: answer.sdp
        },
        status: "connected"
      });
      console.log(`[CallSignalingService] Sent ICE restart answer for call ${callId}`);
    } catch (error) {
      console.error(`[CallSignalingService] Error sending ICE restart answer for call ${callId}:`, error);
    }
  }

  /**
   * Triggers an ICE restart on the given RTCPeerConnection and syncs state with Firestore
   */
  async restartIceConnection(
    callId: string,
    pc: RTCPeerConnection,
    isCaller: boolean
  ): Promise<boolean> {
    if (!callId || !pc || pc.signalingState === "closed") {
      return false;
    }

    try {
      console.log(`[CallSignalingService] Initiating ICE restart for call ${callId} (isCaller: ${isCaller})`);

      // 1. Invoke native restartIce if supported
      if (typeof pc.restartIce === "function") {
        try {
          pc.restartIce();
        } catch (e) {
          console.warn("[CallSignalingService] pc.restartIce warning:", e);
        }
      }

      // 2. Caller renegotiates with iceRestart offer
      if (isCaller) {
        const restartOffer = await pc.createOffer({
          iceRestart: true,
          offerToReceiveAudio: true,
          offerToReceiveVideo: true
        });
        await pc.setLocalDescription(restartOffer);
        await this.sendIceRestartOffer(callId, restartOffer);
      } else {
        // Callee flags status as reconnecting in Firestore to request caller or trigger ice restart
        await this.updateCallStatus(callId, "reconnecting");
      }

      return true;
    } catch (error: any) {
      console.warn(`[CallSignalingService] Error during ICE restart attempt:`, error);
      return false;
    }
  }

  /**
   * Detects network interruptions during an active call and triggers an automatic attempt to re-establish the ICE connection.
   * 
   * Monitors:
   * 1. Browser online/offline events
   * 2. RTCPeerConnection iceConnectionState (disconnected, failed)
   * 3. RTCPeerConnection connectionState (disconnected, failed)
   * 
   * Provides automatic retry throttling, exponential backoff, and full cleanup.
   */
  attachNetworkInterruptionWatcher(options: NetworkInterruptionWatcherOptions): NetworkInterruptionWatcher {
    const {
      callId,
      peerConnection: pc,
      isCaller,
      onInterrupted,
      onReconnecting,
      onReconnected,
      onReconnectionFailed,
      maxAttempts = 4,
      retryIntervalMs = 3500,
      debounceMs = 1500
    } = options;

    let isReconnecting = false;
    let attemptsCount = 0;
    let debounceTimer: any = null;
    let retryIntervalTimer: any = null;
    let isCleanedUp = false;

    const notifyReconnecting = (attempt: number) => {
      try {
        onReconnecting?.(attempt, maxAttempts);
      } catch (e) {
        console.warn("[CallSignalingService] onReconnecting callback error:", e);
      }
    };

    const notifyReconnected = () => {
      try {
        onReconnected?.();
      } catch (e) {
        console.warn("[CallSignalingService] onReconnected callback error:", e);
      }
    };

    const notifyFailed = (reason: string) => {
      try {
        onReconnectionFailed?.(reason);
      } catch (e) {
        console.warn("[CallSignalingService] onReconnectionFailed callback error:", e);
      }
    };

    const triggerIceRestartAttempt = async (): Promise<boolean> => {
      if (isCleanedUp || !pc || pc.signalingState === "closed") {
        return false;
      }

      if (attemptsCount >= maxAttempts) {
        console.warn(`[CallSignalingService] Reconnection max attempts (${maxAttempts}) reached for call ${callId}`);
        notifyFailed("সর্বোচ্চ চেষ্টার পরও নেটওয়ার্ক সংযোগ পুনঃস্থাপন করা সম্ভব হয়নি।");
        return false;
      }

      isReconnecting = true;
      attemptsCount += 1;
      console.log(`[CallSignalingService] Auto ICE Reconnection Attempt ${attemptsCount}/${maxAttempts} for call ${callId}`);
      notifyReconnecting(attemptsCount);

      const success = await this.restartIceConnection(callId, pc, isCaller);

      // Schedule subsequent verification / retry if still disconnected
      if (retryIntervalTimer) clearTimeout(retryIntervalTimer);
      retryIntervalTimer = setTimeout(() => {
        if (isCleanedUp) return;
        const currentIceState = pc.iceConnectionState;
        const currentConnState = pc.connectionState;
        
        const isStillDisconnected = 
          currentIceState === "disconnected" || 
          currentIceState === "failed" || 
          currentConnState === "disconnected" || 
          currentConnState === "failed";

        if (isStillDisconnected && attemptsCount < maxAttempts) {
          triggerIceRestartAttempt();
        } else if (isStillDisconnected && attemptsCount >= maxAttempts) {
          notifyFailed("নেটওয়ার্ক ত্রুটির কারণে কল সংযোগ বিচ্ছিন্ন হয়ে গেছে।");
        }
      }, retryIntervalMs);

      return success;
    };

    const handleInterruptionDetected = (reason: string) => {
      if (isCleanedUp || !pc || pc.signalingState === "closed") return;

      console.warn(`[CallSignalingService] Network interruption detected (${reason}) on call ${callId}`);
      try {
        onInterrupted?.(reason);
      } catch {}

      // Debounce trigger to allow transient network jitter to resolve or batch rapid events
      if (debounceTimer) clearTimeout(debounceTimer);
      debounceTimer = setTimeout(() => {
        debounceTimer = null;
        if (isCleanedUp) return;

        const currentIceState = pc.iceConnectionState;
        const currentConnState = pc.connectionState;
        const isOffline = typeof navigator !== "undefined" && !navigator.onLine;

        if (
          isOffline ||
          currentIceState === "disconnected" ||
          currentIceState === "failed" ||
          currentConnState === "disconnected" ||
          currentConnState === "failed"
        ) {
          triggerIceRestartAttempt();
        }
      }, debounceMs);
    };

    const handleIceConnectionStateChange = () => {
      if (isCleanedUp || !pc) return;
      const state = pc.iceConnectionState;
      console.log(`[CallSignalingService] PeerConnection ICE State: ${state}`);

      if (state === "disconnected" || state === "failed") {
        handleInterruptionDetected(`ice_${state}`);
      } else if (state === "connected" || state === "completed") {
        if (isReconnecting || attemptsCount > 0) {
          console.log(`[CallSignalingService] ICE connection successfully restored for call ${callId}`);
          isReconnecting = false;
          attemptsCount = 0;
          if (debounceTimer) clearTimeout(debounceTimer);
          if (retryIntervalTimer) clearTimeout(retryIntervalTimer);
          notifyReconnected();
        }
      }
    };

    const handleConnectionStateChange = () => {
      if (isCleanedUp || !pc) return;
      const state = pc.connectionState;
      console.log(`[CallSignalingService] PeerConnection Connection State: ${state}`);

      if (state === "disconnected" || state === "failed") {
        handleInterruptionDetected(`conn_${state}`);
      } else if (state === "connected") {
        if (isReconnecting || attemptsCount > 0) {
          isReconnecting = false;
          attemptsCount = 0;
          if (debounceTimer) clearTimeout(debounceTimer);
          if (retryIntervalTimer) clearTimeout(retryIntervalTimer);
          notifyReconnected();
        }
      }
    };

    const handleBrowserOffline = () => {
      handleInterruptionDetected("browser_offline");
    };

    const handleBrowserOnline = () => {
      console.log(`[CallSignalingService] Browser returned online. Retrying ICE connection for call ${callId}`);
      if (isCleanedUp) return;
      if (debounceTimer) clearTimeout(debounceTimer);
      triggerIceRestartAttempt();
    };

    // Attach DOM & WebRTC listeners
    if (typeof window !== "undefined") {
      window.addEventListener("offline", handleBrowserOffline);
      window.addEventListener("online", handleBrowserOnline);
    }

    pc.addEventListener("iceconnectionstatechange", handleIceConnectionStateChange);
    pc.addEventListener("connectionstatechange", handleConnectionStateChange);

    const cleanup = () => {
      isCleanedUp = true;
      if (debounceTimer) clearTimeout(debounceTimer);
      if (retryIntervalTimer) clearTimeout(retryIntervalTimer);

      if (typeof window !== "undefined") {
        window.removeEventListener("offline", handleBrowserOffline);
        window.removeEventListener("online", handleBrowserOnline);
      }

      try {
        pc.removeEventListener("iceconnectionstatechange", handleIceConnectionStateChange);
        pc.removeEventListener("connectionstatechange", handleConnectionStateChange);
      } catch {}
    };

    return {
      cleanup,
      restartIceNow: () => triggerIceRestartAttempt(),
      getIsReconnecting: () => isReconnecting,
      getAttemptsCount: () => attemptsCount
    };
  }

  /**
   * Utility to detect network interruptions and trigger automatic ICE connection re-establishment
   */
  detectNetworkInterruptionsAndAutoRestart(options: NetworkInterruptionWatcherOptions): NetworkInterruptionWatcher {
    return this.attachNetworkInterruptionWatcher(options);
  }

  /**
   * Unsubscribe and cleanup all listeners for a given call session
   */
  cleanupCallSignaling(callId: string) {
    if (!callId) return;
    const subs = this.activeSubscriptions.get(callId);
    if (subs && subs.length > 0) {
      subs.forEach((unsub) => {
        try {
          unsub();
        } catch (e) {
          console.warn("[CallSignalingService] Error unsubscribing listener:", e);
        }
      });
      this.activeSubscriptions.delete(callId);
    }
  }

  /**
   * Teardown all active signaling subscriptions
   */
  teardownAll() {
    this.activeSubscriptions.forEach((subs) => {
      subs.forEach((unsub) => {
        try {
          unsub();
        } catch {}
      });
    });
    this.activeSubscriptions.clear();
  }
}

export const callSignalingService = new CallSignalingService();
export default callSignalingService;
