import { Vehicle, VehicleReview } from './types';

export const CATEGORY_CHIPS = [
  { id: 'all', label: 'সকল', icon: '🚗' },
  { id: 'van', label: 'ভ্যান গাড়ি', icon: '🛞' },
  { id: 'autorickshaw', label: 'অটো রিকশা / ইজিবাইক', icon: '🛺' },
  { id: 'cng', label: 'সিএনজি', icon: '🛵' },
  { id: 'nosimon', label: 'নছিমন / করিমন / ভটভটি', icon: '🚜' },
  { id: 'pickup', label: 'পিকআপ', icon: '🛻' },
  { id: 'microbus', label: 'মাইক্রোবাস', icon: '🚐' },
  { id: 'car', label: 'প্রাইভেট কার', icon: '🏎️' },
  { id: 'ambulance', label: 'জরুরি অ্যাম্বুলেন্স', icon: '🚑' },
  { id: 'truck', label: 'ট্রাক / মিনি ট্রাক', icon: '🚚' },
  { id: 'bus', label: 'বাস', icon: '🚌' },
  { id: 'motorcycle', label: 'মোটরসাইকেল', icon: '🏍️' }
];

export interface RouteFareItem {
  id: string;
  from: string;
  to: string;
  distance: string;
  autoFare: string;
  vanFare: string;
  cngFare: string;
  reserveFare: string;
  note?: string;
}

export const PUTHIA_ROUTE_FARES: RouteFareItem[] = [
  {
    id: 'rf-1',
    from: 'পুঠিয়া সদর / রাজবাড়ি',
    to: 'বানেশ্বর বাজার',
    distance: '৫.৫ কিমি',
    autoFare: '৳২০',
    vanFare: '৳২৫',
    cngFare: '৳৩০',
    reserveFare: '৳১২০ - ১৫০',
    note: 'লোকাল অটো প্রতি ৫ মিনিটে ছাড়ে'
  },
  {
    id: 'rf-2',
    from: 'পুঠিয়া সদর',
    to: 'বেলপুকুরিয়া বাইপাস',
    distance: '১০.২ কিমি',
    autoFare: '৳৩৫',
    vanFare: '৳৪০',
    cngFare: '৳৪০',
    reserveFare: '৳২০০ - ২৫০',
    note: 'মহাসড়ক ধরে দ্রুত যাতায়াত'
  },
  {
    id: 'rf-3',
    from: 'পুঠিয়া সদর',
    to: 'ভালুকগাছি মোড়',
    distance: '৬.০ কিমি',
    autoFare: '৳২৫',
    vanFare: '৳৩০',
    cngFare: '৳৩৫',
    reserveFare: '৳১৫০ - ১৮০',
    note: 'গ্রামীণ পাকা সড়ক'
  },
  {
    id: 'rf-4',
    from: 'পুঠিয়া সদর',
    to: 'শিলমাড়িয়া বাজার',
    distance: '১১.৫ কিমি',
    autoFare: '৳৪০',
    vanFare: '৳৪৫',
    cngFare: '৳৫০',
    reserveFare: '৳২৫০ - ৩০০',
    note: 'মালামাল পরিবহনে নছিমন ও পিকআপ সহজলভ্য'
  },
  {
    id: 'rf-5',
    from: 'পুঠিয়া সদর',
    to: 'জিউপাড়া ইউনিয়ন / বাজার',
    distance: '৭.৫ কিমি',
    autoFare: '৳২৫',
    vanFare: '৳৩০',
    cngFare: '৳৩৫',
    reserveFare: '৳১৬০ - ২০০',
    note: 'লোকাল অটো ও ভ্যান সার্বক্ষণিক চলে'
  },
  {
    id: 'rf-6',
    from: 'বানেশ্বর হাট / বাজার',
    to: 'রাজশাহী সদর (তালাইমারী / রেলগেট)',
    distance: '১৫.০ কিমি',
    autoFare: '৳৫০',
    vanFare: 'N/A',
    cngFare: '৳৬০',
    reserveFare: '৳৩৫০ - ৪০০',
    note: 'সিএনজি ও লোকাল বাস সরাসরি চলাচল করে'
  },
  {
    id: 'rf-7',
    from: 'পুঠিয়া উপজেলা স্বাস্থ্য কমপ্লেক্স',
    to: 'রাজশাহী মেডিকেল কলেজ (জরুরি অ্যাম্বুলেন্স)',
    distance: '২৬.০ কিমি',
    autoFare: 'N/A',
    vanFare: 'N/A',
    cngFare: 'N/A',
    reserveFare: '৳১,৫০০ - ২,২০০',
    note: 'অক্সিজেন ও লাইফ সাপোর্টসহ ২৪ ঘণ্টা প্রস্তুত'
  }
];

export const SERVICE_TYPES = [
  { id: 'hourly', label: 'ঘণ্টাভিত্তিক', icon: '⏱️' },
  { id: 'daily', label: 'দৈনিক', icon: '📅' },
  { id: 'monthly', label: 'মাসিক', icon: '📆' },
  { id: 'long_distance', label: 'দূরপাল্লা', icon: '🛣️' },
  { id: 'local', label: 'স্থানীয়', icon: '🏙️' },
  { id: 'airport', label: 'বিমানবন্দর', icon: '✈️' },
  { id: 'wedding', label: 'বিয়ের অনুষ্ঠান', icon: '💒' },
  { id: 'tour', label: 'ভ্রমণ', icon: '🧳' },
  { id: 'office', label: 'অফিস/ব্যবসা', icon: '🏢' },
  { id: 'cargo', label: 'মালামাল পরিবহন', icon: '📦' }
];

export const PUTHIA_UNIONS = [
  'পুঠিয়া সদর',
  'বানেশ্বর',
  'বেলপুকুরিয়া',
  'ভালুকগাছি',
  'জিউপাড়া',
  'শিলমাড়িয়া'
];

export const PUTHIA_AREAS = [
  'পুঠিয়া বাজার / পৌরসভা',
  'বানেশ্বর বাজার',
  'বেলপুকুরিয়া বাইপাস',
  'মোল্লাপাড়া',
  'ভালুকগাছি মোড়',
  'জিউপাড়া বাসস্ট্যান্ড',
  'শিলমাড়িয়া বাজার'
];

export const initialVehicles: Vehicle[] = [
  {
    id: 'van-puthia-1',
    slug: 'charger-van-puthia-sadar',
    name: 'চার্জার ভ্যান / ব্যাটারি ভ্যান (পুঠিয়া সদর ও পৌর এলাকা)',
    type: 'van',
    typeLabel: 'ভ্যান গাড়ি',
    brand: 'লোকাল চার্জার ভ্যান',
    model: 'ব্যাটারি চালিত মোটর ভ্যান',
    modelYear: '২০২৩',
    imageUrl: '/logo.svg',
    gallery: ['/logo.svg'],
    seatCapacity: 6,
    isAC: false,
    fuelType: 'ব্যাটারি চার্জার',
    transmission: 'ম্যানুয়াল',
    luggageCapacity: 'মালামাল ও যাত্রী বহনযোগ্য',
    driverOption: 'with_driver',
    services: ['hourly', 'daily', 'local', 'cargo'],
    serviceArea: ['পুঠিয়া পৌরসভা', 'পুঠিয়া বাজার', 'রাজবাড়ি', 'রামজীবনপুর'],
    location: {
      union: 'পুঠিয়া সদর',
      area: 'পুঠিয়া বাজার ভ্যান স্ট্যান্ড',
      address: 'পুঠিয়া রাজবাড়ি মোড় ও বাজার সংলগ্ন',
      lat: 24.366,
      lng: 88.831
    },
    pricing: {
      hourly: 150,
      daily: 600,
      perKm: 15
    },
    provider: {
      id: 'prov-van-1',
      name: 'মো: মোতালেব মিয়া',
      businessName: 'পুঠিয়া সদর লোকাল ভ্যান সার্ভিস',
      profileImage: '/logo.svg',
      isVerified: true,
      verificationStatus: 'verified',
      rating: 4.8,
      phone: '01734567891',
      whatsapp: '01734567891',
      serviceArea: 'পুঠিয়া সদর ও পৌর এলাকা',
      address: 'পুঠিয়া বাজার',
      union: 'পুঠিয়া সদর',
      area: 'পুঠিয়া বাজার',
      totalVehicles: 2
    },
    driverInfo: {
      name: 'মো: মোতালেব মিয়া',
      experience: '৮ বছর অভিজ্ঞতা',
      phone: '01734567891',
      rating: 4.8,
      licenseVerified: true
    },
    rules: {
      minBookingHours: 1,
      maxPassengers: 6,
      rulesText: 'বাজারের মালামাল, ধান-চাল ও স্থানীয় যাতায়াতে প্রস্তুত।'
    },
    rating: 4.8,
    reviewCount: 22,
    isFeatured: true,
    status: 'published',
    createdAt: '2026-02-01',
    description: 'পুঠিয়া বাজারের ভেতরে যেকোনো বাসা বদল, ধান-চাল পরিবহন কিংবা হাটের দিনে স্বল্প দূরত্বের যাতায়াতে সুলভ মূল্যের চার্জার ভ্যান।'
  },
  {
    id: 'auto-puthia-1',
    slug: 'easy-bike-auto-puthia-baneshwar',
    name: '৬-আসন ইজিবাইক অটো (পুঠিয়া ⇄ বানেশ্বর লোকাল ও রিজার্ভ)',
    type: 'autorickshaw',
    typeLabel: 'অটো রিকশা',
    brand: 'Easy Bike',
    model: '৬ সিটার হাই-স্পিড অটো',
    modelYear: '২০২৪',
    imageUrl: '/logo.svg',
    gallery: ['/logo.svg'],
    seatCapacity: 6,
    isAC: false,
    fuelType: 'ব্যাটারি চার্জার',
    transmission: 'অটো',
    driverOption: 'with_driver',
    services: ['hourly', 'daily', 'local', 'tour'],
    serviceArea: ['পুঠিয়া সদর', 'বানেশ্বর বাজার', 'বেলপুকুরিয়া', 'জিউপাড়া'],
    location: {
      union: 'পুঠিয়া সদর',
      area: 'থানা মোড় স্ট্যান্ড',
      address: 'পুঠিয়া থানা সংলগ্ন',
      lat: 24.368,
      lng: 88.832
    },
    pricing: {
      hourly: 250,
      daily: 1200,
      perKm: 12
    },
    provider: {
      id: 'prov-auto-1',
      name: 'মো: সজিব হোসেন',
      businessName: 'পুঠিয়া এক্সপ্রেস ইজিবাইক সার্ভিস',
      profileImage: '/logo.svg',
      isVerified: true,
      verificationStatus: 'verified',
      rating: 4.9,
      phone: '01745678912',
      whatsapp: '01745678912',
      serviceArea: 'পুঠিয়া ও বানেশ্বর রুট',
      address: 'থানা মোড়, পুঠিয়া',
      union: 'পুঠিয়া সদর',
      area: 'থানা মোড়',
      totalVehicles: 3
    },
    driverInfo: {
      name: 'মো: সজিব হোসেন',
      experience: '৫ বছর অভিজ্ঞতা',
      phone: '01745678912',
      rating: 4.9,
      licenseVerified: true
    },
    rules: {
      minBookingHours: 1,
      maxPassengers: 6,
      rulesText: 'পরিচ্ছন্ন সিট ও নিরাপদ ড্রাইভিং।'
    },
    rating: 4.9,
    reviewCount: 38,
    isFeatured: true,
    status: 'published',
    createdAt: '2026-02-05',
    description: 'পুঠিয়া থেকে বানেশ্বর বা আশেপাশের সকল ইউনিয়নে রিজার্ভ কিংবা জরুরি যাতায়াতের জন্য প্রস্তুত পরিচ্ছন্ন ইজিবাইক।'
  },
  {
    id: 'cng-puthia-1',
    slug: 'cng-auto-puthia-rajshahi-natore',
    name: '৪-৫ আসন সিএনজি (পুঠিয়া ⇄ রাজশাহী সদর ও নাটোর রিজার্ভ)',
    type: 'cng',
    typeLabel: 'সিএনজি',
    brand: 'Bajaj',
    model: 'RE ৪-স্ট্রোক সিএনজি',
    modelYear: '২০২২',
    imageUrl: '/logo.svg',
    gallery: ['/logo.svg'],
    seatCapacity: 5,
    isAC: false,
    fuelType: 'সিএনজি ও পেট্রোল',
    transmission: 'ম্যানুয়াল',
    driverOption: 'with_driver',
    services: ['hourly', 'daily', 'long_distance', 'local'],
    serviceArea: ['পুঠিয়া', 'বানেশ্বর', 'রাজশাহী সদর', 'নাটোর সদর'],
    location: {
      union: 'পুঠিয়া সদর',
      area: 'পুঠিয়া বাইপাস',
      address: 'ঢাকা-রাজশাহী হাইওয়ে বাইপাস মোড়',
      lat: 24.364,
      lng: 88.835
    },
    pricing: {
      hourly: 350,
      daily: 1800,
      perKm: 16
    },
    provider: {
      id: 'prov-cng-1',
      name: 'মো: জাহিদ হাসান',
      businessName: 'পুঠিয়া হাইওয়ে সিএনজি স্ট্যান্ড',
      profileImage: '/logo.svg',
      isVerified: true,
      verificationStatus: 'verified',
      rating: 4.7,
      phone: '01767891234',
      whatsapp: '01767891234',
      serviceArea: 'পুঠিয়া, নাটোর ও রাজশাহী',
      address: 'বাইপাস মোড়, পুঠিয়া',
      union: 'পুঠিয়া সদর',
      area: 'পুঠিয়া বাইপাস',
      totalVehicles: 4
    },
    driverInfo: {
      name: 'মো: জাহিদ হাসান',
      experience: '৭ বছর অভিজ্ঞতা',
      phone: '01767891234',
      rating: 4.7,
      licenseVerified: true
    },
    rules: {
      minBookingHours: 2,
      maxPassengers: 5,
      rulesText: 'হাইওয়ে ট্রিপে দ্রুত ও নিরাপদ সার্ভিস।'
    },
    rating: 4.7,
    reviewCount: 29,
    isFeatured: true,
    status: 'published',
    createdAt: '2026-02-10',
    description: 'দ্রুত রাজশাহী রেলওয়ে স্টেশন, রাজশাহী মেডিকেল কলেজ বা নাটোর সদরে জরুরি কাজের জন্য নির্ভরযোগ্য সিএনজি।'
  },
  {
    id: 'nosimon-puthia-1',
    slug: 'nosimon-troller-korimon-puthia',
    name: 'নছিমন / করিমন / পাওয়ার ভটভটি (কৃষি পণ্য, আম ও ধান পরিবহন)',
    type: 'nosimon',
    typeLabel: 'নছিমন / করিমন',
    brand: 'গ্রামীণ ট্রলার',
    model: '১৬ হর্সপাওয়ার শ্যালো ইঞ্জিন নছিমন',
    modelYear: '২০২৩',
    imageUrl: '/logo.svg',
    gallery: ['/logo.svg'],
    seatCapacity: 3,
    isAC: false,
    fuelType: 'ডিজেল',
    transmission: 'ম্যানুয়াল',
    luggageCapacity: '১.৫ টন মালামাল ও লোড',
    driverOption: 'with_driver',
    services: ['hourly', 'daily', 'cargo', 'local'],
    serviceArea: ['শিলমাড়িয়া', 'ভালুকগাছি', 'জিউপাড়া', 'বানেশ্বর হাট'],
    location: {
      union: 'শিলমাড়িয়া',
      area: 'শিলমাড়িয়া হাট সংলগ্ন',
      address: 'শিলমাড়িয়া বাজার, পুঠিয়া',
      lat: 24.390,
      lng: 88.850
    },
    pricing: {
      hourly: 300,
      daily: 1500
    },
    provider: {
      id: 'prov-nos-1',
      name: 'মো: সোলেমান আলী',
      businessName: 'কৃষক বন্ধু নছিমন ও মালামাল পরিবহন',
      profileImage: '/logo.svg',
      isVerified: true,
      verificationStatus: 'verified',
      rating: 4.8,
      phone: '01789123456',
      whatsapp: '01789123456',
      serviceArea: 'পুঠিয়ার সকল ইউনিয়ন ও হাটবাজার',
      address: 'শিলমাড়িয়া, পুঠিয়া',
      union: 'শিলমাড়িয়া',
      area: 'শিলমাড়িয়া হাট',
      totalVehicles: 2
    },
    driverInfo: {
      name: 'মো: সোলেমান আলী',
      experience: '১০ বছর অভিজ্ঞতা',
      phone: '01789123456',
      rating: 4.8,
      licenseVerified: true
    },
    rules: {
      rulesText: 'মাঠের ফসল, আম, ধান, খড় ও নির্মাণ সামগ্রী পরিবহনে পারদর্শী।'
    },
    rating: 4.8,
    reviewCount: 19,
    isFeatured: true,
    status: 'published',
    createdAt: '2026-02-12',
    description: 'পুঠিয়ার আম বাগান থেকে বানেশ্বর হাটে আম নেওয়া, ধান-পাট বা বাড়ি তৈরির বালু-ইট পরিবহনে শক্তিশালী নছিমন গাড়ি।'
  },
  {
    id: 'pickup-puthia-1',
    slug: 'tata-ace-pickup-baneshwar-puthia',
    name: 'Tata Ace ১ টন ছোট পিকআপ (পুঠিয়া ও বানেশ্বর ফল ও মালামাল পরিবহন)',
    type: 'pickup',
    typeLabel: 'পিকআপ',
    brand: 'Tata',
    model: 'Ace Gold এক্সট্রা লোডার',
    modelYear: '২০২৩',
    imageUrl: '/logo.svg',
    gallery: ['/logo.svg'],
    seatCapacity: 2,
    isAC: false,
    fuelType: 'ডিজেল',
    transmission: 'ম্যানুয়াল',
    luggageCapacity: '১ টন ভার বহনে সক্ষম',
    driverOption: 'with_driver',
    services: ['daily', 'cargo', 'local', 'long_distance'],
    serviceArea: ['পুঠিয়া', 'বানেশ্বর', 'রাজশাহী', 'নাটোর', 'ঢাকা'],
    location: {
      union: 'বানেশ্বর',
      area: 'বানেশ্বর আম আড়ৎ সংলগ্ন',
      address: 'বানেশ্বর বাজার, পুঠিয়া',
      lat: 24.350,
      lng: 88.800
    },
    pricing: {
      hourly: 450,
      daily: 2500,
      perKm: 22
    },
    provider: {
      id: 'prov-pic-1',
      name: 'মো: কামাল হোসেন',
      businessName: 'বানেশ্বর পিকআপ ও পার্সেল সার্ভিস',
      profileImage: '/logo.svg',
      isVerified: true,
      verificationStatus: 'verified',
      rating: 4.9,
      phone: '01712345679',
      whatsapp: '01712345679',
      serviceArea: 'রাজশাহী ও সারা বাংলাদেশ',
      address: 'বানেশ্বর আম বাজার',
      union: 'বানেশ্বর',
      area: 'বানেশ্বর বাজার',
      totalVehicles: 3
    },
    driverInfo: {
      name: 'মো: কামাল হোসেন',
      experience: '৯ বছর অভিজ্ঞতা',
      phone: '01712345679',
      rating: 4.9,
      licenseVerified: true
    },
    rules: {
      rulesText: 'ফলমূল ও ফার্নিচার নিরাপদে গন্তব্যে পৌঁছে দেওয়া হয়।'
    },
    rating: 4.9,
    reviewCount: 41,
    isFeatured: true,
    status: 'published',
    createdAt: '2026-02-15',
    description: 'বানেশ্বর হাট থেকে আম, ফলমূল, ফার্নিচার বা মালামাল রাজশাহী শহর কিংবা দূরপাল্লায় পরিবহনের জন্য ১ টন পিকআপ।'
  },
  {
    id: 'ambulance-puthia-1',
    slug: 'emergency-ambulance-puthia-health-complex',
    name: 'উপজেলা স্বাস্থ্য কমপ্লেক্স সংলগ্ন ২৪/৭ এসি অ্যাম্বুলেন্স',
    type: 'ambulance',
    typeLabel: 'জরুরি অ্যাম্বুলেন্স',
    brand: 'Toyota',
    model: 'HiAce মেডিকেল ভ্যান',
    modelYear: '২০২২',
    imageUrl: '/logo.svg',
    gallery: ['/logo.svg'],
    seatCapacity: 4,
    isAC: true,
    fuelType: 'অকটেন / সিএনজি',
    transmission: 'ম্যানুয়াল',
    luggageCapacity: 'মেডিকেল ইকুইপমেন্ট ও স্ট্রেচার',
    driverOption: 'with_driver',
    services: ['hourly', 'local', 'long_distance'],
    serviceArea: ['পুঠিয়া উপজেলা', 'রাজশাহী মেডিকেল কলেজ', 'বগুড়া', 'ঢাকা'],
    location: {
      union: 'পুঠিয়া সদর',
      area: 'উপজেলা স্বাস্থ্য কমপ্লেক্স গেট',
      address: 'হাসপাতাল রোড, পুঠিয়া',
      lat: 24.365,
      lng: 88.833
    },
    pricing: {
      hourly: 800,
      perKm: 25,
      longDistanceNote: 'পুঠিয়া থেকে রামেক হাসপাতাল জরুরি কল।'
    },
    provider: {
      id: 'prov-amb-1',
      name: 'মো: সোহেল রানা',
      businessName: 'পুঠিয়া লাইফ লাইন অ্যাম্বুলেন্স সার্ভিস',
      profileImage: '/logo.svg',
      isVerified: true,
      verificationStatus: 'verified',
      rating: 5.0,
      phone: '01712998877',
      whatsapp: '01712998877',
      serviceArea: '২৪ ঘণ্টা পুঠিয়া ও রাজশাহী অঞ্চল',
      address: 'স্বাস্থ্য কমপ্লেক্স সংলগ্ন, পুঠিয়া',
      union: 'পুঠিয়া সদর',
      area: 'পুঠিয়া সদর',
      totalVehicles: 2
    },
    driverInfo: {
      name: 'মো: সোহেল রানা',
      experience: '১২ বছর অভিজ্ঞতা',
      phone: '01712998877',
      rating: 5.0,
      licenseVerified: true
    },
    rules: {
      rulesText: 'জরুরি রোগীদের জন্য ২৪ ঘণ্টা সার্বক্ষণিক অক্সিজেন সুবিধা।'
    },
    rating: 5.0,
    reviewCount: 52,
    isFeatured: true,
    status: 'published',
    createdAt: '2026-01-20',
    description: 'জরুরি রোগী স্থানান্তরে সার্বক্ষণিক অক্সিজেন, স্ট্রেচার ও প্যারামেডিক সাপোর্ট সহ পুঠিয়ার জরুরি অ্যাম্বুলেন্স।'
  },
  {
    id: 'veh-1',
    slug: 'toyota-noah-voxy-microbus-puthia',
    name: 'Toyota Noah X (৭-৮ আসন VIP মাইক্রোবাস)',
    type: 'microbus',
    typeLabel: 'মাইক্রোবাস',
    brand: 'Toyota',
    model: 'Noah X Hybrid',
    modelYear: '২০১৮',
    imageUrl: '/logo.svg', 
    gallery: [
      '/logo.svg', 
      '/logo.svg', 
      '/logo.svg'
    ],
    seatCapacity: 8,
    isAC: true,
    fuelType: 'অকটেন ও হাইব্রিড',
    transmission: 'অটোমেটিক',
    luggageCapacity: '৪ টি বড় লাগেজ',
    driverOption: 'with_driver',
    services: ['daily', 'long_distance', 'wedding', 'tour', 'airport'],
    serviceArea: ['পুঠিয়া', 'বানেশ্বর', 'রাজশাহী শহর', 'ঢাকা', 'সমগ্র বাংলাদেশ'],
    location: {
      union: 'পুঠিয়া সদর',
      area: 'পুঠিয়া বাজার, রাজবাড়ি মোড়',
      address: 'পুঠিয়া বাসস্ট্যান্ড সংলগ্ন, পুঠিয়া পৌরসভা',
      lat: 24.366,
      lng: 88.831
    },
    pricing: {
      hourly: 600,
      halfDay: 2200,
      daily: 3800,
      monthly: 65000,
      perKm: 14,
      longDistanceRate: 4200,
      longDistanceNote: 'ফুয়েল ও টোল ব্যতিত। ড্রাইভারের খোরাকি আলোচনা সাপেক্ষে।'
    },
    provider: {
      id: 'prov-1',
      name: 'মো: রফিকুল ইসলাম',
      businessName: 'পুঠিয়া রেন্ট-এ-কার & ট্রাভেলস',
      profileImage: '/logo.svg', 
      isVerified: true,
      verificationStatus: 'verified',
      rating: 4.9,
      phone: '01712345678',
      whatsapp: '01712345678',
      email: 'puthia.rentacar@gmail.com',
      serviceArea: 'পুঠিয়া উপজেলা ও সারা দেশ',
      address: 'রাজবাড়ি রোড, পুঠিয়া বাজার',
      union: 'পুঠিয়া সদর',
      area: 'পুঠিয়া বাজার',
      totalVehicles: 6
    },
    driverInfo: {
      name: 'মো: রানা আহমেদ',
      experience: '৮ বছর অভিজ্ঞতা',
      phone: '01712345678',
      rating: 4.9,
      licenseVerified: true
    },
    rules: {
      minBookingHours: 4,
      maxPassengers: 8,
      fuelIncluded: false,
      tollIncluded: false,
      parkingIncluded: false,
      extraHourCharge: 400,
      cancellationPolicy: 'যাত্রার ২৪ ঘণ্টা পূর্বে বাতিল করলে সম্পূর্ণ ফ্রী।',
      rulesText: 'গাড়িতে ধূমপান নিষেধ। অতিরিক্ত যাত্রী বা মালামাল বহনে পূর্বেই আলোচনা করুন।'
    },
    rating: 4.8,
    reviewCount: 34,
    isFeatured: true,
    status: 'published',
    bookedDates: ['2026-08-15', '2026-08-16'],
    createdAt: '2026-01-10',
    description: 'পুঠিয়া রাজবাড়ি ও আশেপাশের যেকোনো ট্যুর, বিয়ের অনুষ্ঠান, ঢাকা/রাজশাহী এয়ারপোর্ট ট্রিপ বা পারিবারিক সফরের জন্য আরামদায়ক এসি নোয়া মাইক্রোবাস।'
  },
  {
    id: 'veh-2',
    slug: 'toyota-allion-premium-car-baneshwar',
    name: 'Toyota Allion G-Superior (এসি প্রাইভেট কার)',
    type: 'car',
    typeLabel: 'প্রাইভেট কার',
    brand: 'Toyota',
    model: 'Allion G',
    modelYear: '২০১৯',
    imageUrl: '/logo.svg', 
    gallery: [
      '/logo.svg', 
      '/logo.svg'
    ],
    seatCapacity: 5,
    isAC: true,
    fuelType: 'অকটেন',
    transmission: 'অটোমেটিক',
    luggageCapacity: '২ টি ট্রলি ব্যাগ',
    driverOption: 'with_driver',
    services: ['hourly', 'daily', 'wedding', 'airport', 'office'],
    serviceArea: ['বানেশ্বর', 'পুঠিয়া', 'রাজশাহী', 'নাটোর', 'পাবনা'],
    location: {
      union: 'বানেশ্বর',
      area: 'বানেশ্বর বাজার বাইপাস',
      address: 'বানেশ্বর ডিগ্রি কলেজ মোড়, পুঠিয়া',
      lat: 24.372,
      lng: 88.810
    },
    pricing: {
      hourly: 500,
      halfDay: 1800,
      daily: 3200,
      monthly: 55000,
      perKm: 12,
      longDistanceRate: 3500,
      longDistanceNote: 'পাসঞ্জার ফুয়েল চার্জ যুক্ত হতে পারে।'
    },
    provider: {
      id: 'prov-2',
      name: 'মো: আব্দুল মতিন',
      businessName: 'বানেশ্বর কার রেন্টাল এন্ড সার্ভিস',
      profileImage: '/logo.svg', 
      isVerified: true,
      verificationStatus: 'verified',
      rating: 4.8,
      phone: '01812345678',
      whatsapp: '01812345678',
      email: 'baneshwar.car@gmail.com',
      serviceArea: 'বানেশ্বর, পুঠিয়া ও রাজশাহী পথ',
      address: 'বানেশ্বর বাজার মোড়',
      union: 'বানেশ্বর',
      area: 'বানেশ্বর বাজার',
      totalVehicles: 4
    },
    driverInfo: {
      name: 'শরিফুল ইসলাম',
      experience: '৬ বছর অভিজ্ঞতা',
      phone: '01812345678',
      rating: 4.8,
      licenseVerified: true
    },
    rules: {
      minBookingHours: 2,
      maxPassengers: 4,
      fuelIncluded: false,
      tollIncluded: false,
      parkingIncluded: false,
      extraHourCharge: 350,
      cancellationPolicy: 'যাত্রার ১২ ঘণ্টা পূর্বে ফ্রিতে বাতিল।'
    },
    rating: 4.9,
    reviewCount: 28,
    isFeatured: true,
    status: 'published',
    bookedDates: [],
    createdAt: '2026-02-01',
    description: 'বানেশ্বর ও পুঠিয়া অঞ্চলের নির্ভরযোগ্য এসি এলিয়ন প্রাইভেট কার। ভিআইপি মুভমেন্ট, অফিসিয়াল ভিজিট ও পারিবারিক সফরের জন্য পারফেক্ট।'
  },
  {
    id: 'veh-3',
    slug: 'hiace-emergency-ambulance-puthia',
    name: 'Toyota HiAce এয়ারকন্ডিশনড আইসিইউ অ্যাম্বুলেন্স',
    type: 'ambulance',
    typeLabel: 'অ্যাম্বুলেন্স',
    brand: 'Toyota',
    model: 'HiAce High Roof Ambulance',
    modelYear: '২০২০',
    imageUrl: '/logo.svg', 
    gallery: [
      '/logo.svg'
    ],
    seatCapacity: 6,
    isAC: true,
    fuelType: 'ডিজেল ও সিএনজি',
    transmission: 'ম্যানুয়াল',
    luggageCapacity: 'অক্সিজেন সিলিন্ডার ও পেশেন্ট ট্রলি',
    driverOption: 'with_driver',
    services: ['hourly', 'daily', 'long_distance', 'local'],
    serviceArea: ['পুঠিয়া', 'উপজেলা হাসপাতাল', 'রাজশাহী মেডিকেল', 'ঢাকা'],
    location: {
      union: 'পুঠিয়া সদর',
      area: 'উপজেলা স্বাস্থ্য কমপ্লেক্স এর সামনে',
      address: 'হাসপাতাল রোড, পুঠিয়া',
      lat: 24.368,
      lng: 88.835
    },
    pricing: {
      hourly: 400,
      halfDay: 1500,
      daily: 3000,
      perKm: 15,
      longDistanceNote: 'জরুরি অক্সিজেন সিলিন্ডার ও সাইরেন সুবিধা অন্তর্ভুক্ত।'
    },
    provider: {
      id: 'prov-3',
      name: 'পুঠিয়া জরুরি এম্বুলেন্স সেবা',
      businessName: 'পুঠিয়া জনসেবা অ্যাম্বুলেন্স সার্ভিস',
      profileImage: '/logo.svg', 
      isVerified: true,
      verificationStatus: 'verified',
      rating: 5.0,
      phone: '01799887766',
      whatsapp: '01799887766',
      serviceArea: '২৪ ঘণ্টা পুঠিয়া ও আশেপাশের সকল হাসপাতাল ট্রিপ',
      address: 'হাসপাতাল গেট, পুঠিয়া',
      union: 'পুঠিয়া সদর',
      area: 'উপজেলা স্বাস্থ্য কমপ্লেক্স',
      totalVehicles: 3
    },
    driverInfo: {
      name: 'মো: আল-আমিন (ফার্স্ট এইড প্রশিক্ষিত)',
      experience: '১০ বছর জরুরি সার্ভিস অভিজ্ঞতা',
      phone: '01799887766',
      rating: 5.0,
      licenseVerified: true
    },
    rules: {
      minBookingHours: 1,
      maxPassengers: 4,
      fuelIncluded: true,
      tollIncluded: false,
      parkingIncluded: true,
      extraHourCharge: 300,
      cancellationPolicy: 'জরুরি রোগীর ক্ষেত্রে বাতিল ফি মুক্ত।'
    },
    rating: 5.0,
    reviewCount: 45,
    isFeatured: true,
    status: 'published',
    bookedDates: [],
    createdAt: '2026-01-05',
    description: '২৪ ঘণ্টা জরুরি অক্সিজেন সাপোর্ট, স্ট্রেচার ও অভিজ্ঞ ড্রাইভারসহ পুঠিয়া উপজেলা স্বাস্থ্য কমপ্লেক্স এবং রাজশাহী মেডিকেল কলেজের উদ্দেশ্যে প্রস্তুত।'
  },
  {
    id: 'veh-4',
    slug: 'mahindra-pickup-cargo-belpukuria',
    name: 'Mahindra Bolero 1.5 Ton প্যাকড পিকআপ',
    type: 'pickup',
    typeLabel: 'পিকআপ',
    brand: 'Mahindra',
    model: 'Bolero Maxi Truck',
    modelYear: '২০২১',
    imageUrl: '/logo.svg', 
    gallery: [
      '/logo.svg'
    ],
    seatCapacity: 3,
    isAC: false,
    fuelType: 'ডিজেল',
    transmission: 'ম্যানুয়াল',
    luggageCapacity: '১.৫ টন মালামাল',
    driverOption: 'with_driver',
    services: ['cargo', 'daily', 'local', 'long_distance'],
    serviceArea: ['বেলপুকুরিয়া', 'পুঠিয়া', 'বানেশ্বর', 'রাজশাহী জেলা', 'নাটোর'],
    location: {
      union: 'বেলপুকুরিয়া',
      area: 'বেলপুকুরিয়া বাইপাস মোড়',
      address: 'বেলপুকুরিয়া বাজার সংলগ্ন, পুঠিয়া',
      lat: 24.360,
      lng: 88.800
    },
    pricing: {
      hourly: 400,
      halfDay: 1500,
      daily: 2800,
      perKm: 18,
      longDistanceNote: 'পণ্য ওঠানো-নামানোর জন্য হেলপার সুবিধা রয়েছে।'
    },
    provider: {
      id: 'prov-4',
      name: 'বেলপুকুরিয়া ট্রান্সপোর্ট এজেন্সি',
      businessName: 'বেলপুকুরিয়া মালামাল পরিবহন সার্ভিস',
      profileImage: '/logo.svg', 
      isVerified: true,
      verificationStatus: 'verified',
      rating: 4.7,
      phone: '01911223344',
      whatsapp: '01911223344',
      serviceArea: 'বেলপুকুরিয়া, পুঠিয়া ও উত্তরবঙ্গ রোড',
      address: 'বেলপুকুরিয়া বাইপাস',
      union: 'বেলপুকুরিয়া',
      area: 'বেলপুকুরিয়া বাজার',
      totalVehicles: 5
    },
    driverInfo: {
      name: 'মো: বেল্লাল হোসেন',
      experience: '৭ বছর অভিজ্ঞতা',
      phone: '01911223344',
      rating: 4.7,
      licenseVerified: true
    },
    rules: {
      minBookingHours: 2,
      maxPassengers: 2,
      fuelIncluded: false,
      tollIncluded: false,
      parkingIncluded: false,
      extraHourCharge: 250,
      cancellationPolicy: 'লোডিংয়ের ২ ঘণ্টা পূর্বে বাতিল করলে চার্জ নেই।'
    },
    rating: 4.7,
    reviewCount: 19,
    isFeatured: false,
    status: 'published',
    bookedDates: [],
    createdAt: '2026-02-10',
    description: 'বাসা পরিবর্তন, দোকান বা হাটের মালামাল, কৃষিপণ্য ও নির্মাণ সামগ্রী নিরাপদে গন্তব্যে পৌঁছানোর জন্য উপযুক্ত মহিন্দ্রা পিকআপ।'
  },
  {
    id: 'veh-5',
    slug: 'covered-van-tata-14ft-puthia',
    name: 'Tata 14 Feet কাভার্ড ভ্যান (বৃষ্টি ও সুরক্ষাবেষ্টিত)',
    type: 'covered_van',
    typeLabel: 'কাভার্ড ভ্যান',
    brand: 'Tata',
    model: 'LPT 407 Covered Van',
    modelYear: '২০২০',
    imageUrl: '/logo.svg', 
    gallery: [
      '/logo.svg'
    ],
    seatCapacity: 3,
    isAC: false,
    fuelType: 'ডিজেল',
    transmission: 'ম্যানুয়াল',
    luggageCapacity: '৩.৫ টন নিরাপদে ঢাকা প্যাকড গুডস',
    driverOption: 'with_driver',
    services: ['cargo', 'long_distance', 'office'],
    serviceArea: ['পুঠিয়া', 'রাজশাহী', 'ঢাকা', 'চট্টগ্রাম', 'সারা দেশ'],
    location: {
      union: 'পুঠিয়া সদর',
      area: 'পৌরসভা ট্রাক স্ট্যান্ড',
      address: 'রাজশাহী-নাটোর হাইওয়ে, পুঠিয়া',
      lat: 24.365,
      lng: 88.828
    },
    pricing: {
      daily: 4500,
      perKm: 22,
      longDistanceNote: 'ঢাকা বা চট্টগ্রাম রুটের জন্য আকর্ষণীয় এককালীন ভাড়া প্যাকেজ।'
    },
    provider: {
      id: 'prov-5',
      name: 'পুঠিয়া কুরিয়ার ও কাভার্ড ভ্যান সার্ভিস',
      businessName: 'শাহ আমানত ট্রান্সপোর্ট সার্ভিস',
      profileImage: '/logo.svg', 
      isVerified: true,
      verificationStatus: 'verified',
      rating: 4.8,
      phone: '01755443322',
      whatsapp: '01755443322',
      serviceArea: 'সারা বাংলাদেশে নিরাপদ মালামাল পরিবহন',
      address: 'ট্রাক স্ট্যান্ড, পুঠিয়া',
      union: 'পুঠিয়া সদর',
      area: 'পুঠিয়া বাজার',
      totalVehicles: 8
    },
    driverInfo: {
      name: 'মো: জহুরুল ইসলাম',
      experience: '১২ বছর অভিজ্ঞতা',
      phone: '01755443322',
      rating: 4.8,
      licenseVerified: true
    },
    rules: {
      fuelIncluded: false,
      tollIncluded: false,
      parkingIncluded: false,
      cancellationPolicy: 'যাত্রার ২৪ ঘণ্টা পূর্বে বাতিলের সুযোগ।'
    },
    rating: 4.8,
    reviewCount: 22,
    isFeatured: false,
    status: 'published',
    bookedDates: [],
    createdAt: '2026-01-20',
    description: 'বৃষ্টি বা রোদ হতে মালামাল বা ফ্যাক্টরি প্রডাক্ট সম্পূর্ণ সুরক্ষিত রাখতে ১৪ ফিটের নির্ভরযোগ্য কাভার্ড ভ্যান সার্ভিস।'
  },
  {
    id: 'veh-6',
    slug: 'cng-4-stroke-autorickshaw-jiopara',
    name: 'Bajaj RE 4-Stroke সিএনজি অটোরিকশা',
    type: 'cng',
    typeLabel: 'সিএনজি',
    brand: 'Bajaj',
    model: 'RE 4S Compact',
    modelYear: '২০২২',
    imageUrl: '/logo.svg', 
    gallery: [
      '/logo.svg'
    ],
    seatCapacity: 4,
    isAC: false,
    fuelType: 'সিএনজি ও পেট্রোল',
    transmission: 'ম্যানুয়াল',
    luggageCapacity: '১-২ টি ছোট ব্যাগ',
    driverOption: 'with_driver',
    services: ['local', 'hourly', 'daily'],
    serviceArea: ['জিউপাড়া', 'পুঠিয়া সদর', 'বানেশ্বর', 'মোল্লাপাড়া'],
    location: {
      union: 'জিউপাড়া',
      area: 'জিউপাড়া বাসস্ট্যান্ড',
      address: 'জিউপাড়া বাজার মোড়, পুঠিয়া',
      lat: 24.380,
      lng: 88.850
    },
    pricing: {
      hourly: 150,
      halfDay: 600,
      daily: 1200,
      perKm: 10,
      longDistanceNote: 'পুঠিয়া উপজেলার ভেতরে দ্রুত ভ্রমণের জন্য উপযুক্ত।'
    },
    provider: {
      id: 'prov-6',
      name: 'মো: জালাল উদ্দিন',
      businessName: 'জিউপাড়া স্থানীয় সিএনজি স্ট্যান্ড',
      profileImage: '/logo.svg', 
      isVerified: false,
      verificationStatus: 'pending',
      rating: 4.6,
      phone: '01833221100',
      whatsapp: '01833221100',
      serviceArea: 'জিউপাড়া ও স্থানীয় সকল রোড',
      address: 'জিউপাড়া বাসস্ট্যান্ড',
      union: 'জিউপাড়া',
      area: 'জিউপাড়া বাসস্ট্যান্ড',
      totalVehicles: 2
    },
    driverInfo: {
      name: 'মো: জালাল উদ্দিন',
      experience: '৫ বছর অভিজ্ঞতা',
      phone: '01833221100',
      rating: 4.6,
      licenseVerified: true
    },
    rules: {
      minBookingHours: 1,
      maxPassengers: 4,
      fuelIncluded: true,
      extraHourCharge: 120
    },
    rating: 4.6,
    reviewCount: 14,
    isFeatured: false,
    status: 'published',
    bookedDates: [],
    createdAt: '2026-02-15',
    description: 'কম খরচে পুঠিয়া উপজেলার ভেতরের যেকোনো গ্রামে বা বাজারে ভ্রমণের জন্য ঝটপট সিএনজি সার্ভিস।'
  },
  {
    id: 'veh-7',
    slug: 'easy-bike-autorickshaw-bhalukgachi',
    name: 'ব্যাটারিচালিত অটো রিকশা (ইজি বাইক)',
    type: 'autorickshaw',
    typeLabel: 'অটোরিকশা',
    brand: 'Local Eco-Bike',
    model: '5-Battery Heavy Duty',
    modelYear: '২০২৩',
    imageUrl: '/logo.svg', 
    gallery: [
      '/logo.svg'
    ],
    seatCapacity: 6,
    isAC: false,
    fuelType: 'ইলেকট্রিক ব্যাটারি',
    transmission: 'অটোমেটিক',
    luggageCapacity: 'বাজারের থলে বা হালকা মালামাল',
    driverOption: 'with_driver',
    services: ['local', 'hourly'],
    serviceArea: ['ভালুকগাছি', 'পুঠিয়া সদর', 'ধোপাপাড়া', 'শিলমাড়িয়া'],
    location: {
      union: 'ভালুকগাছি',
      area: 'ভালুকগাছি বাজার',
      address: 'ভালুকগাছি ইউনিয়ন পরিষদ মোড়',
      lat: 24.390,
      lng: 88.820
    },
    pricing: {
      hourly: 100,
      halfDay: 450,
      daily: 800,
      longDistanceNote: 'সংক্ষিপ্ত দূরত্বের গ্রামীণ যাতায়াতের জন্য।'
    },
    provider: {
      id: 'prov-7',
      name: 'মো: সারোয়ার হোসেন',
      businessName: 'ভালুকগাছি ইজি বাইক সমিতি',
      profileImage: '/logo.svg', 
      isVerified: true,
      verificationStatus: 'verified',
      rating: 4.7,
      phone: '01722334455',
      whatsapp: '01722334455',
      serviceArea: 'ভালুকগাছি ও পার্শ্ববর্তী গ্রামসমূহ',
      address: 'ভালুকগাছি বাজার',
      union: 'ভালুকগাছি',
      area: 'ভালুকগাছি বাজার',
      totalVehicles: 3
    },
    driverInfo: {
      name: 'মো: সারোয়ার হোসেন',
      experience: '৪ বছর অভিজ্ঞতা',
      phone: '01722334455',
      rating: 4.7,
      licenseVerified: true
    },
    rules: {
      minBookingHours: 1,
      maxPassengers: 6,
      fuelIncluded: true,
      extraHourCharge: 80
    },
    rating: 4.7,
    reviewCount: 12,
    isFeatured: false,
    status: 'published',
    bookedDates: [],
    createdAt: '2026-02-18',
    description: 'ভালুকগাছি ও পুঠিয়ার গ্রামীণ কাঁচা-পাকা রাস্তায় স্বাচ্ছন্দ্যে যাতায়াতের পরিবেশবান্ধব অটো রিকশা।'
  },
  {
    id: 'veh-8',
    slug: 'bajaj-pulsar-motorcycle-silmaria',
    name: 'Bajaj Pulsar 150 SD (মোটরসাইকেল রাইড / রেন্ট)',
    type: 'motorcycle',
    typeLabel: 'মোটরসাইকেল',
    brand: 'Bajaj',
    model: 'Pulsar 150 Twin Disc',
    modelYear: '২০২৩',
    imageUrl: '/logo.svg', 
    gallery: [
      '/logo.svg'
    ],
    seatCapacity: 2,
    isAC: false,
    fuelType: 'অকটেন',
    transmission: 'ম্যানুয়াল',
    luggageCapacity: '১ টি হেলমেট ও ছোট ব্যাকপ্যাক',
    driverOption: 'both',
    services: ['hourly', 'daily', 'local', 'office'],
    serviceArea: ['শিলমাড়িয়া', 'পুঠিয়া', 'বানেশ্বর', 'রাজশাহী city'],
    location: {
      union: 'শিলমাড়িয়া',
      area: 'শিলমাড়িয়া বাজার',
      address: 'শিলমাড়িয়া স্কুল গেট, পুঠিয়া',
      lat: 24.350,
      lng: 88.860
    },
    pricing: {
      hourly: 150,
      halfDay: 600,
      daily: 1000,
      perKm: 8,
      longDistanceNote: 'স্মার্ট হেলমেট ফ্রী দেয়া হবে।'
    },
    provider: {
      id: 'prov-8',
      name: 'তৌহিদুর রহমান',
      businessName: 'পুঠিয়া বাইক রেন্টাল সার্ভিস',
      profileImage: '/logo.svg', 
      isVerified: true,
      verificationStatus: 'verified',
      rating: 4.9,
      phone: '01844556677',
      whatsapp: '01844556677',
      serviceArea: 'পুঠিয়া উপজেলা ও রাজশাহী রুটে এক্সপ্রেস বাইক',
      address: 'শিলমাড়িয়া বাজার',
      union: 'শিলমাড়িয়া',
      area: 'শিলমাড়িয়া বাজার',
      totalVehicles: 2
    },
    driverInfo: {
      name: 'তৌহিদুর রহমান',
      experience: '৫ বছর অভিজ্ঞতা',
      phone: '01844556677',
      rating: 4.9,
      licenseVerified: true
    },
    rules: {
      minBookingHours: 1,
      maxPassengers: 1,
      fuelIncluded: false,
      cancellationPolicy: 'ফ্রী বাতিল ব্যবস্থা।'
    },
    rating: 4.9,
    reviewCount: 16,
    isFeatured: false,
    status: 'published',
    bookedDates: [],
    createdAt: '2026-02-20',
    description: 'দ্রুত যেকোনো জরুরি কাজে পুঠিয়া বা রাজশাহীতে যাতায়াতের জন্য পারফেক্ট ১৫০ সিসি বাইক রাইড ও রেন্ট সার্ভিস।'
  },
  {
    id: 'veh-9',
    slug: 'toyota-coaster-30-seat-bus-puthia',
    name: 'Toyota Coaster (৩০ সিট বিলাসবহুল মিনি বাস)',
    type: 'bus',
    typeLabel: 'বাস',
    brand: 'Toyota',
    model: 'Coaster VIP AC',
    modelYear: '২০১৯',
    imageUrl: '/logo.svg', 
    gallery: [
      '/logo.svg'
    ],
    seatCapacity: 30,
    isAC: true,
    fuelType: 'ডিজেল',
    transmission: 'ম্যানুয়াল',
    luggageCapacity: 'বিশাল সাইড ও ব্যাক লাগেজ স্পেস',
    driverOption: 'with_driver',
    services: ['daily', 'wedding', 'tour', 'long_distance', 'office'],
    serviceArea: ['পুঠিয়া', 'রাজশাহী', 'পাবনা', 'বগুড়া', 'ঢাকা', 'সারা দেশ'],
    location: {
      union: 'পুঠিয়া সদর',
      area: 'পুঠিয়া বাজার বাস টার্মিনাল',
      address: 'বাস টার্মিনাল, পুঠিয়া পৌরসভা',
      lat: 24.367,
      lng: 88.830
    },
    pricing: {
      daily: 8500,
      monthly: 180000,
      longDistanceRate: 9500,
      longDistanceNote: 'পিকনিক, স্কুল/কলেজ ট্যুর ও বিয়ের পার্টির জন্য স্পেশাল বুকিং डिस्काउंट।'
    },
    provider: {
      id: 'prov-9',
      name: 'পুঠিয়া ট্রাভেলস & ট্যুরিজম',
      businessName: 'পুঠিয়া রয়েল বাস সার্ভিস',
      profileImage: '/logo.svg', 
      isVerified: true,
      verificationStatus: 'verified',
      rating: 4.8,
      phone: '01711002233',
      whatsapp: '01711002233',
      serviceArea: 'সারা বাংলাদেশে গ্রুপের ভ্রমণ ও ইভেন্ট বাস',
      address: 'বাস স্ট্যান্ড, পুঠিয়া',
      union: 'পুঠিয়া সদর',
      area: 'পুঠিয়া বাজার',
      totalVehicles: 4
    },
    driverInfo: {
      name: 'মো: এরশাদ আলী',
      experience: '১৫ বছর অভিজ্ঞতা',
      phone: '01711002233',
      rating: 4.8,
      licenseVerified: true
    },
    rules: {
      minBookingHours: 8,
      maxPassengers: 30,
      fuelIncluded: false,
      tollIncluded: false,
      parkingIncluded: false,
      cancellationPolicy: 'যাত্রার ৪৮ ঘণ্টা পূর্বে জানালে ৫০% রিফান্ড।'
    },
    rating: 4.8,
    reviewCount: 31,
    isFeatured: true,
    status: 'published',
    bookedDates: ['2026-08-25'],
    createdAt: '2026-01-01',
    description: 'বিয়ের বরযাত্রী, শিক্ষা সফর, পিকনিক কিংবা বড় পারিবারিক ভ্রমণের জন্য আরামদায়ক ৩০ সিটের বিলাসবহুল এসি কোস্টার বাস।'
  }
];

export const sampleReviews: VehicleReview[] = [
  {
    id: 'rev-1',
    vehicleId: 'veh-1',
    vehicleName: 'টয়োটা নোয়া এক্স হাইব্রিড (৭ সিট এসি)',
    driverName: 'মো: রানা হোসেন',
    driverPhone: '01711223344',
    userName: 'তাহমিদ হাসান',
    userAvatar: '/logo.svg', 
    rating: 5,
    driverRating: 5,
    safetyRating: 5,
    punctualityRating: 5,
    behaviorRating: 5,
    cleanlinessRating: 5,
    date: '০২ আগস্ট, ২০২৬',
    rideDate: '০১ আগস্ট, ২০২৬',
    rideRoute: 'পুঠিয়া বাজার → রাজশাহী বিমানবন্দর',
    farePaid: '৳৩,৫০০',
    feedbackTags: ['নিরাপদ ড্রাইভিং', 'সময়নিষ্ঠ', 'বিনয়ী চালক', 'পরিচ্ছন্ন গাড়ি'],
    recommended: true,
    verifiedRide: true,
    comment: 'পুঠিয়া থেকে ফ্যামিলি নিয়ে কক্সবাজার ও রাজশাহী ট্যুরে গিয়েছিলাম। ড্রাইভার রানা ভাই চমৎকার ও অত্যন্ত নিরাপদ ড্রাইভ করেছেন। গাড়ি একদম পরিচ্ছন্ন ও সময়মতো পৌঁছেছেন।'
  },
  {
    id: 'rev-2',
    vehicleId: 'auto-puthia-1',
    vehicleName: 'মিশুক অটো রিকশা (৬ সিট)',
    driverName: 'মো: রফিকুল ইসলাম',
    driverPhone: '01712345601',
    userName: 'মো: সাজ্জাদ হোসেন',
    userAvatar: '/logo.svg',
    rating: 5,
    driverRating: 4.8,
    safetyRating: 5,
    punctualityRating: 5,
    behaviorRating: 5,
    cleanlinessRating: 4.5,
    date: '২৫ জুলাই, ২০২৬',
    rideDate: '২৪ জুলাই, ২০২৬',
    rideRoute: 'পুঠিয়া রাজবাড়ি → বানেশ্বর বাজার',
    farePaid: '৳১৫০ (রিজার্ভ)',
    feedbackTags: ['সময়নিষ্ঠ', 'ন্যায্য ভাড়া', 'বিনয়ী চালক'],
    recommended: true,
    verifiedRide: true,
    comment: 'রফিক ভাই খুবই সৎ ও ভদ্র মানুষ। ফোন দেওয়ার ৫ মিনিটের মধ্যে রাজবাড়ির গেটে অটো নিয়ে এসেছিলেন। অতিরিক্ত কোনো ভাড়া দাবি করেননি।'
  },
  {
    id: 'rev-3',
    vehicleId: 'van-puthia-1',
    vehicleName: 'চার্জার ইঞ্জিন ভ্যান গাড়ি',
    driverName: 'মো: সালাম উদ্দিন',
    driverPhone: '01711122233',
    userName: 'আবুল কালাম আজাদ',
    userAvatar: '/logo.svg',
    rating: 5,
    driverRating: 5,
    safetyRating: 4.8,
    punctualityRating: 5,
    behaviorRating: 5,
    cleanlinessRating: 4.5,
    date: '২০ জুলাই, ২০২৬',
    rideDate: '১৯ জুলাই, ২০২৬',
    rideRoute: 'বানেশ্বর হাট → ঝলমলিয়া হাট',
    farePaid: '৳২৫০',
    feedbackTags: ['দক্ষ চালক', 'ন্যায্য ভাড়া', 'মালামাল বহনে সহায়ক'],
    recommended: true,
    verifiedRide: true,
    comment: 'হাটের মালামাল ও আম নেওয়ার জন্য সালাম ভাইয়ের ভ্যান নিয়েছিলাম। ভাই নিজে হাতে বস্তা উঠিয়ে দিয়েছেন এবং সাবধানে পৌঁছে দিয়েছেন।'
  },
  {
    id: 'rev-4',
    vehicleId: 'cng-puthia-1',
    vehicleName: 'সিএনজি ফোর-স্ট্রোক অটো',
    driverName: 'আনিসুর রহমান',
    driverPhone: '01733445566',
    userName: 'নাসরিন সুলতানা',
    userAvatar: '/logo.svg',
    rating: 5,
    driverRating: 5,
    safetyRating: 5,
    punctualityRating: 4.8,
    behaviorRating: 5,
    cleanlinessRating: 5,
    date: '১৫ জুলাই, ২০২৬',
    rideDate: '১৫ জুলাই, ২০২৬',
    rideRoute: 'পুঠিয়া বাসস্ট্যান্ড → বেলপুকুরিয়া বাইপাস',
    farePaid: '৳২০০',
    feedbackTags: ['নিরাপদ ড্রাইভিং', 'পরিচ্ছন্ন গাড়ি', 'পরিবারের জন্য নিরাপদ'],
    recommended: true,
    verifiedRide: true,
    comment: 'মহিলা ও শিশুদের নিয়ে যাতায়াতের জন্য আনিস ভাইয়ের সিএনজি খুবই নিরাপদ মনে হয়েছে। স্পিড লিমিট মেনে ড্রাইভিং করেন।'
  },
  {
    id: 'rev-5',
    vehicleId: 'veh-3',
    vehicleName: 'জরুরি অক্সিজেন অ্যাম্বুলেন্স',
    driverName: 'মো: আব্দুল মতিন',
    driverPhone: '01712998877',
    userName: 'ড. কামরুল ইসলাম',
    userAvatar: '/logo.svg', 
    rating: 5,
    driverRating: 5,
    safetyRating: 5,
    punctualityRating: 5,
    behaviorRating: 5,
    cleanlinessRating: 5,
    date: '১০ জুলাই, ২০২৬',
    rideDate: '১০ জুলাই, ২০২৬',
    rideRoute: 'পুঠিয়া স্বাস্থ্য কমপ্লেক্স → রাজশাহী মেডিকেল (RMCH)',
    farePaid: '৳১,৮০০',
    feedbackTags: ['দ্রুত সেবা', 'জরুরি সময়ে পাশে', 'দক্ষ চালক'],
    recommended: true,
    verifiedRide: true,
    comment: 'জরুরি রুগীকে রাজশাহী মেডিকেলে নেওয়ার জন্য রাত ২টায় ফোন দিয়েছিলাম। ৫ মিনিটের মধ্যে এম্বুলেন্স নিয়ে মতিন ভাই হাজির ছিলেন। অক্সিজেন সাপোর্টও পারফেক্ট ছিল।'
  },
  {
    id: 'rev-6',
    vehicleId: 'pickup-puthia-1',
    vehicleName: 'টাটা এইস ১-টন খোলা পিকআপ',
    driverName: 'মো: বাবুল হোসেন',
    driverPhone: '01755667788',
    userName: 'ফারুক হোসেন',
    userAvatar: '/logo.svg',
    rating: 4.8,
    driverRating: 5,
    safetyRating: 4.9,
    punctualityRating: 4.7,
    behaviorRating: 5,
    cleanlinessRating: 4.6,
    date: '০৫ জুলাই, ২০২৬',
    rideDate: '০৪ জুলাই, ২০২৬',
    rideRoute: 'জিউপাড়া ইউনিয়ন → বানেশ্বর মোকাম',
    farePaid: '৳১,২০০',
    feedbackTags: ['মালামাল বহনে সহায়ক', 'ন্যায্য ভাড়া', 'দক্ষ চালক'],
    recommended: true,
    verifiedRide: true,
    comment: 'আমের মৌসুমে বাগান থেকে বানেশ্বর আড়তে ক্যারেট বহনের জন্য বাবুল ভাইয়ের পিকআপ ভাড়া করি। সময়মতো মালামাল লোড-আনলোড করতে সাহায্য করেছেন।'
  }
];
