import { Category } from "./types";

export const CATEGORIES: Category[] = [
  {
    id: "upazila_intro",
    label: "🏛️ উপজেলা পরিচিতি",
    itemIds: [
      "upazila_history",
      "upazila_geography",
      "upazila_population",
      "upazila_map",
      "upazila_admin",
      "upazila_tourism",
      "upazila_info",
      "roads_transport",
      "notable_persons",
    ],
    items: [
      { id: "upazila_history", label: "📜 পুঠিয়ার ইতিহাস" },
      { id: "upazila_geography", label: "🌍 ভৌগোলিক পরিচিতি" },
      { id: "upazila_population", label: "👥 জনসংখ্যা" },
      { id: "upazila_map", label: "🗺️ মানচিত্র" },
      { id: "upazila_admin", label: "🏢 প্রশাসনিক কাঠামো" },
      { id: "upazila_tourism", label: "📸 দর্শনীয় স্থান" },
      { id: "upazila_info", label: "ℹ️ গুরুত্বপূর্ণ তথ্য" },
      { id: "roads_transport", label: "🚌 যোগাযোগ ও পরিবহন ব্যবস্থা" },
      { id: "notable_persons", label: "🏅 স্থানীয় কৃতী ব্যক্তিত্ব" },
    ],
  },
  {
    id: "union_group",
    label: "🗺️ ইউনিয়ন",
    itemIds: [
      "union_profiles",
      "chairman_members",
      "union_offices",
      "union_services",
      "union_maps",
      "union_contact",
    ],
    items: [
      { id: "union_profiles", label: "📍 প্রতিটি ইউনিয়নের প্রোফাইল" },
      { id: "chairman_members", label: "👥 চেয়ারম্যান ও সদস্যবৃন্দ" },
      { id: "union_offices", label: "🏢 ইউনিয়ন অফিস" },
      { id: "union_services", label: "⚙️ ইউনিয়নভিত্তিক সেবা" },
      { id: "union_maps", label: "🗺️ ইউনিয়নের মানচিত্র" },
      { id: "union_contact", label: "📞 যোগাযোগ" },
    ],
  },
  {
    id: "village_database",
    label: "🏘️ গ্রাম তথ্যভাণ্ডার",
    itemIds: [
      "village_list",
      "village_history",
      "village_population",
      "village_education",
      "village_religion",
      "village_notable_persons",
      "village_gallery",
      "village_map",
    ],
    items: [
      { id: "village_list", label: "📋 গ্রামের তালিকা" },
      { id: "village_history", label: "📜 গ্রামের ইতিহাস" },
      { id: "village_population", label: "👥 জনসংখ্যা" },
      { id: "village_education", label: "🎓 শিক্ষা প্রতিষ্ঠান" },
      { id: "village_religion", label: "🕌 ধর্মীয় প্রতিষ্ঠান" },
      { id: "village_notable_persons", label: "⭐ উল্লেখযোগ্য ব্যক্তি" },
      { id: "village_gallery", label: "🖼️ ছবি গ্যালারি" },
      { id: "village_map", label: "🗺️ অবস্থান মানচিত্র" },
    ],
  },
  {
    id: "agri_weather",
    label: "🌾 কৃষি খামার ও আবহাওয়া",
    itemIds: [
      "weather_update",
      "agri_advice",
      "crop_info",
      "fertilizer_seed",
      "agri_office",
      "disease_solve",
      "market_price",
    ],
    items: [
      { id: "weather_update", label: "⛅ আবহাওয়ার আপডেট" },
      { id: "agri_advice", label: "📖 কৃষি পরামর্শ" },
      { id: "crop_info", label: "🌱 ফসল তথ্য" },
      { id: "fertilizer_seed", label: "💧 সার ও বীজ" },
      { id: "agri_office", label: "🏢 কৃষি অফিস" },
      { id: "disease_solve", label: "🐛 রোগবালাই সমাধান" },
      { id: "market_price", label: "💰 বাজারদর" },
    ],
  },
  {
    id: "tourism_heritage",
    label: "📸 ইতিহাস ও পর্যটন",
    itemIds: [
      "puthia_rajbari",
      "temples",
      "historical_places",
      "travel_guide",
      "hotel_transport_info",
      "tourism_photo_gallery",
      "tourism_video_gallery",
    ],
    items: [
      { id: "puthia_rajbari", label: "🏰 পুঠিয়া রাজবাড়ী" },
      { id: "temples", label: "🛕 মন্দির" },
      { id: "historical_places", label: "🏛️ ঐতিহাসিক স্থান" },
      { id: "travel_guide", label: "🧭 ভ্রমণ গাইড" },
      { id: "hotel_transport_info", label: "🏨 হোটেল ও যাতায়াত তথ্য" },
      { id: "tourism_photo_gallery", label: "🖼️ ছবি গ্যালারি" },
      { id: "tourism_video_gallery", label: "🎬 ভিডিও গ্যালারি" },
    ],
  },
  {
    id: "important_contacts",
    label: "📞 গুরুত্বপূর্ণ যোগাযোগ",
    itemIds: [
      "uno_contact",
      "chairman_contact",
      "oc_contact",
      "up_contact",
      "electricity_contact",
      "water_contact",
      "hospital_contact",
      "fire_service_contact",
    ],
    items: [
      { id: "uno_contact", label: "💼 উপজেলা নির্বাহী অফিসার" },
      { id: "chairman_contact", label: "👤 উপজেলা চেয়ারম্যান" },
      { id: "oc_contact", label: "🛡️ থানার ওসি" },
      { id: "up_contact", label: "🏢 ইউনিয়ন পরিষদ" },
      { id: "electricity_contact", label: "⚡ বিদ্যুৎ অফিস" },
      { id: "water_contact", label: "💧 পানি সরবরাহ" },
      { id: "hospital_contact", label: "🏥 হাসপাতাল" },
      { id: "fire_service_contact", label: "🔥 ফায়ার সার্ভিস" },
    ],
  },
  {
    id: "download_center",
    label: "⬇️ ডাউনলোড সেন্টার",
    itemIds: [
      "application_form",
      "important_pdf",
      "certificate_sample",
      "agriculture_guide",
      "education_material",
    ],
    items: [
      { id: "application_form", label: "📄 আবেদন ফরম" },
      { id: "important_pdf", label: "📑 গুরুত্বপূর্ণ PDF" },
      { id: "certificate_sample", label: "📜 নাগরিক সনদ নমুনা" },
      { id: "agriculture_guide", label: "🚜 কৃষি গাইড" },
      { id: "education_material", label: "📚 শিক্ষা উপকরণ" },
    ],
  },
  {
    id: "religious_social",
    label: "🤝 সামাজিক প্রতিষ্ঠান",
    itemIds: ["mosque", "eidgah", "graveyard", "religious_events", "ngo_social", "orphanage"],
    items: [
      { id: "mosque", label: "🕌 মসজিদ" },
      { id: "eidgah", label: "🌅 ঈদগাহ" },
      { id: "graveyard", label: "🪦 কবরস্থান" },
      { id: "religious_events", label: "📅 ধর্মীয় অনুষ্ঠান" },
      { id: "ngo_social", label: "🌍 এনজিও ও সামাজিক উন্নয়ন" },
      { id: "orphanage", label: "🏢 এতিমখানা" },
    ],
  },
  {
    id: "transport_info",
    label: "🚌 পরিবহন তথ্য",
    itemIds: ["bus_schedule", "train_info", "fare_list", "van_auto_info", "transport_map", "bus_counter_emergency"],
    items: [
      { id: "bus_schedule", label: "🚌 বাস সময়সূচী" },
      { id: "train_info", label: "🚆 ট্রেন তথ্য" },
      { id: "fare_list", label: "💰 ভাড়া তালিকা" },
      { id: "van_auto_info", label: "🛺 ভ্যান ও অটোরিকশা" },
      { id: "transport_map", label: "🗺️ স্ট্যান্ড লোকেশন ম্যাপ" },
      { id: "bus_counter_emergency", label: "🚌 বাস কাউন্টার জরুরি নম্বর" },
    ],
  },
  {
    id: "complaints_suggestions",
    label: "💬 অভিযোগ ও পরামর্শ",
    itemIds: [
      "problem_report",
      "citizen_complaint",
      "road_problem",
      "electricity_problem",
      "water_problem",
      "provide_feedback",
      "complaint_status",
    ],
    items: [
      { id: "problem_report", label: "🚨 সমস্যা রিপোর্ট" },
      { id: "citizen_complaint", label: "📄 নাগরিক অভিযোগ" },
      { id: "road_problem", label: "🛣️ রাস্তা সমস্যা" },
      { id: "electricity_problem", label: "⚡ বিদ্যুৎ সমস্যা" },
      { id: "water_problem", label: "💧 পানি সমস্যা" },
      { id: "provide_feedback", label: "💡 মতামত প্রদান" },
      { id: "complaint_status", label: "✅ অভিযোগের অবস্থা" },
    ],
  },
  {
    id: "blood_network",
    label: "🩸 রক্তদাতা নেটওয়ার্ক",
    itemIds: [
      "blood_donor_list",
      "search_blood_group",
      "emergency_blood",
      "blood_donation_reg",
      "blood_donation_history",
    ],
    items: [
      { id: "blood_donor_list", label: "📋 রক্তদাতা তালিকা" },
      { id: "search_blood_group", label: "🔍 রক্তের গ্রুপ অনুসন্ধান" },
      { id: "emergency_blood", label: "🚨 জরুরি রক্ত প্রয়োজন" },
      { id: "blood_donation_reg", label: "📝 রক্তদান নিবন্ধন" },
      { id: "blood_donation_history", label: "📜 সফল রক্তদান ইতিহাস" },
    ],
  },
  {
    id: "govt_services",
    label: "🏛️ সরকারি সেবা",
    itemIds: [
      "ds_birth_reg",
      "ds_death_reg",
      "ds_nid_services",
      "ds_passport",
      "ds_land_services",
      "ds_e_mutation",
      "ds_online_application",
      "ds_govt_office_directory",
    ],
    items: [
      { id: "ds_birth_reg", label: "📝 জন্ম নিবন্ধন" },
      { id: "ds_death_reg", label: "📄 মৃত্যু নিবন্ধন" },
      { id: "ds_nid_services", label: "🪪 জাতীয় পরিচয়পত্র" },
      { id: "ds_passport", label: "🛂 পাসপোর্ট" },
      { id: "ds_land_services", label: "🗺️ ভূমি সেবা" },
      { id: "ds_e_mutation", label: "📑 ই-নামজারি" },
      { id: "ds_online_application", label: "🖱️ অনলাইন আবেদন" },
      { id: "ds_govt_office_directory", label: "🏢 সরকারি অফিস ডিরেক্টরি" },
    ],
  },
  {
    id: "edu_corner",
    label: "🏫 শিক্ষা প্রতিষ্ঠান",
    itemIds: [
      "edu_school",
      "edu_college",
      "edu_madrasha",
      "edu_technical",
      "edu_kindergarten",
      "edu_coaching",
      "edu_library",
    ],
    items: [
      { id: "edu_school", label: "স্কুল" },
      { id: "edu_college", label: "কলেজ" },
      { id: "edu_madrasha", label: "মাদ্রাসা" },
      { id: "edu_technical", label: "কারিগরি শিক্ষা" },
      { id: "edu_kindergarten", label: "কিন্ডারগার্টেন" },
      { id: "edu_coaching", label: "কোচিং সেন্টার" },
      { id: "edu_library", label: "লাইব্রেরি" },
    ],
  },
  {
    id: "agri_info",
    label: "🌾 কৃষি খামার ও আবহাওয়া",
    itemIds: ["agri_weather", "agri_advice", "agri_prices", "agri_officers", "livestock_poultry", "agri_fish_farm", "agri_video_training", "local_nursery", "agri_loans", "agri_diseases", "agri_machinery", "agri_dealers", "agri_calendar"],
    items: [
      { id: "agri_weather", label: "আবহাওয়া" },
      { id: "agri_advice", label: "ফসল চাষের পরামর্শ" },
      { id: "agri_prices", label: "বাজারদর" },
      { id: "agri_officers", label: "কৃষি কর্মকর্তার যোগাযোগ" },
      { id: "livestock_poultry", label: "🐄 প্রাণিসম্পদ" },
      { id: "agri_fish_farm", label: "🐟 মৎস্য খামার" },
      { id: "agri_video_training", label: "🎥 কৃষি ভিডিও/প্রশিক্ষণ" },
      { id: "local_nursery", label: "🌱 নার্সারি" },
      { id: "agri_loans", label: "🌱 কৃষি ঋণ ও সরকারি প্রণোদনা" },
      { id: "agri_diseases", label: "🦠 রোগবালাই ও কীটনাশক পরামর্শ" },
      { id: "agri_machinery", label: "🌾 কৃষি যন্ত্রপাতি ভাড়া/সেবা" },
      { id: "agri_dealers", label: "🌿 সার ও বীজের ডিলার" },
      { id: "agri_calendar", label: "📅 মৌসুমি ফসল ক্যালেন্ডার" },
    ],
  },
  {
    id: "service_providers_menu",
    label: "🛠️ সেবা প্রদানকারী",
    itemIds: [
      "sp_construction",
      "sp_plumbing",
      "sp_electronics",
      "sp_technical",
      "sp_vehicle",
      "sp_lawyer",
      "sp_journalist",
    ],
    items: [
      { id: "sp_construction", label: "🏗️ নির্মাণ ও ডেকোরেশন" },
      { id: "sp_plumbing", label: "🚰 টিউবওয়েল ও স্যানিটারি" },
      { id: "sp_electronics", label: "💻 ইলেকট্রনিক্স সার্ভিসিং" },
      { id: "sp_technical", label: "🔧 টেকনিক্যাল সার্ভিস" },
      { id: "sp_vehicle", label: "🚘 গাড়ি ও বাইক মেকানিক" },
      { id: "sp_lawyer", label: "⚖️ আইনজীবী" },
      { id: "sp_journalist", label: "📰 সাংবাদিক" },
    ],
  },
  {
    id: "business_economy",
    label: "🏪 ব্যবসা ও বাজার",
    itemIds: [
      "shop_grocery",
      "shop_pharmacy",
      "shop_mobile_computer",
      "shop_electronics",
      "shop_clothing_cosmetics",
      "shop_furniture",
      "shop_hardware_sanitary",
      "shop_agri_supplies",
      "shop_sweets_bakery",
      "shop_jewelry",
      "shop_books_stationery",
      "shop_vet_feed",
      "shop_mall_market"
    ],
    items: [
      { id: "shop_grocery", label: "🛒 সুপার শপ / মুদি দোকান" },
      { id: "shop_pharmacy", label: "💊 ফার্মেসি" },
      { id: "shop_mobile_computer", label: "📱 মোবাইল ও কম্পিউটার দোকান" },
      { id: "shop_electronics", label: "⚡ ইলেকট্রনিক্স" },
      { id: "shop_clothing_cosmetics", label: "👗 বস্ত্র ও কসমেটিকস" },
      { id: "shop_furniture", label: "🪑 ফার্নিচার" },
      { id: "shop_hardware_sanitary", label: "🔧 হার্ডওয়্যার ও স্যানিটারি" },
      { id: "shop_agri_supplies", label: "🌾 কৃষি উপকরণের দোকান" },
      { id: "shop_sweets_bakery", label: "🍰 মিষ্টির দোকান ও বেকারি" },
      { id: "shop_jewelry", label: "💍 জুয়েলারি" },
      { id: "shop_books_stationery", label: "📚 বই ও স্টেশনারি" },
      { id: "shop_vet_feed", label: "🐄 পশুখাদ্য ও ভেট শপ" },
      { id: "shop_mall_market", label: "🛍️ শপিং মল / মার্কেট" }
    ],
  },
  {
    id: "emergency_health",
    label: "🚨 জরুরি সেবা",
    itemIds: [
      "rural_electricity",
      "veterinary_doctor",
      "police_contact",
      "fire_service_contact",
      "emergency_ambulance",
      "cyber_helpline",
      "women_children_help",
      "national_helpline",
      "hospital",
      "clinic",
      "doctor",
      "pharmacy",
      "diagnostic",
      "dental",
    ],
    items: [
      { id: "rural_electricity", label: "⚡ পল্লী বিদ্যুৎ অফিস" },
      { id: "veterinary_doctor", label: "🐾 ভেটেরিনারি ডাক্তার" },
      { id: "police_contact", label: "🛡️ পুলিশ" },
      { id: "fire_service_contact", label: "🔥 ফায়ার সার্ভিস" },
      { id: "emergency_ambulance", label: "🚑 অ্যাম্বুলেন্স" },
      { id: "cyber_helpline", label: "💻 সাইবার হেল্পলাইন" },
      { id: "women_children_help", label: "👩‍👧 নারী ও শিশু সহায়তা" },
      { id: "national_helpline", label: "📞 জাতীয় হেল্পলাইন" },
    ],
  },
  {
    id: "youth_career",
    label: "💼 ক্যারিয়ার ও শিক্ষা",
    itemIds: [
      "job_circular",
      "education_coaching",
      "job_local_ads",
      "job_freelance_res",
      "job_training_news",
      "education_scholarship",
      "career_guideline",
    ],
    items: [
      { id: "job_circular", label: "💼 চাকরির খবর" },
      { id: "education_coaching", label: "🏫 শিক্ষা ও কোচিং" },
      { id: "job_local_ads", label: "স্থানীয় চাকরির বিজ্ঞপ্তি" },
      { id: "job_freelance_res", label: "ফ্রিল্যান্সিং রিসোর্স" },
      { id: "job_training_news", label: "প্রশিক্ষণ কর্মশালার খবর" },
      { id: "education_scholarship", label: "🎓 স্কলারশিপ তথ্য" },
      { id: "career_guideline", label: "💡 ক্যারিয়ার গাইডলাইন" },
    ],
  },
  {
    id: "community_engagement",
    label: "🤝 কমিউনিটি ও ইভেন্ট",
    itemIds: [
      "local_news",
      "notice_board",
      "community_programs",
      "sports_activities",
      "cultural_activities",
      "social_organizations",
      "volunteer_network",
      "lost_and_found",
      "photo_video_gallery",
    ],
    items: [
      { id: "local_news", label: "📰 স্থানীয় সংবাদ" },
      { id: "notice_board", label: "📌 নোটিশ বোর্ড" },
      { id: "community_programs", label: "📅 অনুষ্ঠান" },
      { id: "sports_activities", label: "🏆 খেলাধুলা" },
      { id: "cultural_activities", label: "🎭 সাংস্কৃতিক কার্যক্রম" },
      { id: "social_organizations", label: "🏢 সামাজিক সংগঠন" },
      { id: "volunteer_network", label: "🤝 স্বেচ্ছাসেবক নেটওয়ার্ক" },
      { id: "lost_and_found", label: "🔍 হারানো ও পাওয়া" },
      { id: "photo_video_gallery", label: "📸 ছবি ও ভিডিও" },
    ],
  },
  {
    id: "exclusive_features",
    label: "✨ এক্সক্লুসিভ ফিচার",
    itemIds: [
      "digital_id_card",
      "local_vote_survey",
      "citizen_ranking",
      "verified_business",
      "community_badge",
      "upazila_quiz",
      "local_ads",
    ],
    items: [
      { id: "digital_id_card", label: "🪪 ডিজিটাল পরিচিতি কার্ড" },
      { id: "local_vote_survey", label: "📊 স্থানীয় ভোট/জরিপ" },
      { id: "citizen_ranking", label: "🏆 নাগরিক র্যাংকিং" },
      { id: "verified_business", label: "✅ ভেরিফাইড ব্যবসা" },
      { id: "community_badge", label: "🎖️ কমিউনিটি ব্যাজ" },
      { id: "upazila_quiz", label: "🏆 উপজেলা কুইজ ও প্রতিযোগিতা" },
      { id: "local_ads", label: "📢 স্থানীয় স্পন্সর ও বিজ্ঞাপন" },
    ],
  },
  {
    id: "blood_network_group",
    label: "🩸 রক্তদাতা নেটওয়ার্ক",
    itemIds: ["blood_donor_list", "blood_emergency_request"],
    items: [
      { id: "blood_donor_list", label: "🩸 গ্রুপভিত্তিক রক্তদাতা তালিকা" },
      { id: "blood_emergency_request", label: "🆘 জরুরি রক্তের অনুরোধ" },
    ],
  },
];
